export const executiveMetrics = [
  { label: "Projetos ativos", value: "12", delta: "+2 este mês" },
  { label: "Tarefas críticas", value: "17", delta: "5 vencem hoje" },
  { label: "Equipe online", value: "09", delta: "75% presente" },
  { label: "Entregas da semana", value: "28", delta: "+8 concluídas" },
  { label: "Bloqueios", value: "03", delta: "-1 desde ontem" },
  { label: "Aprovações pendentes", value: "06", delta: "2 urgentes" },
  { label: "Eficiência", value: "82%", delta: "+4%" },
  { label: "Risco operacional", value: "Moderado", delta: "monitorado" },
];

export const alerts = [
  {
    title: "Entregas vencendo hoje",
    status: "Urgente",
    count: "05",
    description: "Itens com prazo crítico exigindo resposta rápida do time.",
    tone: "danger" as const,
  },
  {
    title: "Projetos em risco",
    status: "Atenção",
    count: "03",
    description: "Projetos com atraso, bloqueio ou baixo avanço recente.",
    tone: "warning" as const,
  },
  {
    title: "Aprovações pendentes",
    status: "Fila",
    count: "06",
    description: "Pedidos aguardando retorno de liderança ou cliente.",
    tone: "neutral" as const,
  },
  {
    title: "Concluídas hoje",
    status: "Bom ritmo",
    count: "11",
    description: "Tarefas finalizadas nas últimas horas pela equipe.",
    tone: "success" as const,
  },
];

export const workAreas = [
  {
    title: "Projetos",
    description: "Portfólio ativo, líderes, risco e progresso geral.",
    meta: "12 ativos",
    href: "/projetos",
    icon: "PJ",
  },
  {
    title: "Tarefas",
    description: "Fila operacional com foco em prioridade e prazo.",
    meta: "37 abertas",
    href: "/tarefas",
    icon: "TF",
  },
  {
    title: "Equipe",
    description: "Responsáveis, capacidade, carga e performance.",
    meta: "12 membros",
    href: "/equipe",
    icon: "EQ",
  },
  {
    title: "Relatórios",
    description: "Leitura executiva e indicadores resumidos.",
    meta: "8 painéis",
    href: "/relatorios",
    icon: "RL",
  },
];

export const recentActivity = [
  {
    id: 1,
    title: "Projeto Nova Jornada mudou para Em andamento",
    user: "Marina",
    time: "há 12 min",
  },
  {
    id: 2,
    title: "Tarefa Revisar dashboard executivo foi concluída",
    user: "André",
    time: "há 24 min",
  },
  {
    id: 3,
    title: "Bloqueio reportado no projeto Portal de Vendas",
    user: "Lucas",
    time: "há 40 min",
  },
  {
    id: 4,
    title: "Relatório semanal atualizado com novos indicadores",
    user: "Camila",
    time: "há 1h",
  },
];

export const projects = [
  {
    id: 1,
    name: "Nova Jornada",
    owner: "Marina",
    deadline: "08/04/2026",
    progress: 72,
    status: "Em andamento",
    priority: "Alta",
    teamSize: 5,
    tone: "neutral" as const,
  },
  {
    id: 2,
    name: "Portal de Vendas",
    owner: "Lucas",
    deadline: "12/04/2026",
    progress: 48,
    status: "Em risco",
    priority: "Alta",
    teamSize: 4,
    tone: "warning" as const,
  },
  {
    id: 3,
    name: "Painel da Diretoria",
    owner: "Camila",
    deadline: "15/04/2026",
    progress: 90,
    status: "Quase concluído",
    priority: "Média",
    teamSize: 3,
    tone: "success" as const,
  },
  {
    id: 4,
    name: "Operação de Campo",
    owner: "Renato",
    deadline: "22/04/2026",
    progress: 36,
    status: "Aguardando",
    priority: "Média",
    teamSize: 6,
    tone: "danger" as const,
  },
];

export const tasks = [
  {
    id: 1,
    title: "Atualizar dashboard executivo",
    owner: "André",
    status: "Em andamento",
    priority: "Alta",
    deadline: "05/04/2026",
    description: "Refinar leitura rápida para a liderança e revisar indicadores.",
    tone: "neutral" as const,
  },
  {
    id: 2,
    title: "Revisar página da equipe",
    owner: "Marina",
    status: "Em risco",
    priority: "Média",
    deadline: "07/04/2026",
    description: "Melhorar organização visual da capacidade e distribuição.",
    tone: "warning" as const,
  },
  {
    id: 3,
    title: "Criar visão de tarefas",
    owner: "Lucas",
    status: "Concluída",
    priority: "Baixa",
    deadline: "02/04/2026",
    description: "Estruturar cards e filtros iniciais para operação diária.",
    tone: "success" as const,
  },
  {
    id: 4,
    title: "Validar relatório mensal",
    owner: "Camila",
    status: "Pendente",
    priority: "Alta",
    deadline: "09/04/2026",
    description: "Fechar leitura executiva para envio ao time de gestão.",
    tone: "danger" as const,
  },
];

export const teamMembers = [
  {
    name: "André",
    initials: "AN",
    role: "Dados e automação",
    activeTasks: 7,
    projects: 3,
    capacity: "Carga alta",
    performance: 84,
    tone: "warning" as const,
  },
  {
    name: "Marina",
    initials: "MA",
    role: "Coordenação de produto",
    activeTasks: 5,
    projects: 2,
    capacity: "Equilibrada",
    performance: 91,
    tone: "success" as const,
  },
  {
    name: "Lucas",
    initials: "LU",
    role: "Operações",
    activeTasks: 6,
    projects: 4,
    capacity: "Moderada",
    performance: 76,
    tone: "neutral" as const,
  },
  {
    name: "Camila",
    initials: "CA",
    role: "Relatórios e gestão",
    activeTasks: 4,
    projects: 2,
    capacity: "Saudável",
    performance: 88,
    tone: "success" as const,
  },
  {
    name: "Renato",
    initials: "RE",
    role: "Projetos especiais",
    activeTasks: 8,
    projects: 5,
    capacity: "Carga crítica",
    performance: 63,
    tone: "danger" as const,
  },
];

export const academicBoardAreas = [
  {
    name: "Graduação",
    lead: "Marina Alves",
    people: 18,
    deliveries: 24,
    pending: 5,
    efficiency: 88,
    status: "Estável",
    tone: "success" as const,
  },
  {
    name: "Pós-graduação",
    lead: "Lucas Ferreira",
    people: 10,
    deliveries: 16,
    pending: 4,
    efficiency: 81,
    status: "Atenção",
    tone: "warning" as const,
  },
  {
    name: "Secretaria Acadêmica",
    lead: "Camila Duarte",
    people: 14,
    deliveries: 28,
    pending: 6,
    efficiency: 85,
    status: "Em dia",
    tone: "neutral" as const,
  },
  {
    name: "Coordenação Pedagógica",
    lead: "Renato Lima",
    people: 11,
    deliveries: 19,
    pending: 7,
    efficiency: 73,
    status: "Sob pressão",
    tone: "danger" as const,
  },
];

export const academicBoardPeople = [
  {
    name: "Marina Alves",
    initials: "MA",
    area: "Graduação",
    role: "Diretora acadêmica",
    activeTasks: 7,
    pending: 2,
    onTime: 91,
    performance: 93,
    capacity: "Equilibrada",
    tone: "success" as const,
  },
  {
    name: "Lucas Ferreira",
    initials: "LF",
    area: "Pós-graduação",
    role: "Coordenador",
    activeTasks: 8,
    pending: 3,
    onTime: 84,
    performance: 82,
    capacity: "Moderada",
    tone: "neutral" as const,
  },
  {
    name: "Camila Duarte",
    initials: "CD",
    area: "Secretaria Acadêmica",
    role: "Gestão operacional",
    activeTasks: 6,
    pending: 2,
    onTime: 88,
    performance: 87,
    capacity: "Saudável",
    tone: "success" as const,
  },
  {
    name: "Renato Lima",
    initials: "RL",
    area: "Coordenação Pedagógica",
    role: "Coordenador pedagógico",
    activeTasks: 10,
    pending: 5,
    onTime: 71,
    performance: 69,
    capacity: "Carga alta",
    tone: "warning" as const,
  },
];

export const reportHighlights = [
  {
    label: "Leitura do dia",
    value: "5 pontos críticos",
    delta: "3 pedem ação hoje",
  },
  {
    label: "Projetos sob risco",
    value: "3",
    delta: "1 piorou desde ontem",
  },
  {
    label: "Capacidade média",
    value: "82%",
    delta: "estável",
  },
  {
    label: "Pendências abertas",
    value: "23",
    delta: "fila controlada",
  },
];

export const reportTakeaways = [
  "Priorize as entregas com prazo em até 48 horas.",
  "Redistribua carga nas áreas com pressão acima da média.",
  "Feche aprovações pendentes antes de abrir novas frentes.",
];
